/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMonCompteRouteImport } from './routes/_app/mon-compte'
import { Route as AppStockIndexRouteImport } from './routes/_app/stock/index'
import { Route as AppStockMouvementsRouteImport } from './routes/_app/stock/mouvements'
import { Route as AppCatalogueFournisseursRouteImport } from './routes/_app/catalogue/fournisseurs'
import { Route as AppCatalogueCategoriesRouteImport } from './routes/_app/catalogue/categories'
import { Route as AppAdministrationUtilisateursRouteImport } from './routes/_app/administration/utilisateurs'
import { Route as AppAdministrationParametresRouteImport } from './routes/_app/administration/parametres'
import { Route as AppAdministrationEntrepotsRouteImport } from './routes/_app/administration/entrepots'
import { Route as AppStockReceptionsIndexRouteImport } from './routes/_app/stock/receptions/index'
import { Route as AppCatalogueProduitsIndexRouteImport } from './routes/_app/catalogue/produits/index'
import { Route as AppCatalogueProduitsProductIdRouteImport } from './routes/_app/catalogue/produits/$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonCompteRoute = AppMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AppRoute,
} as any)
const AppStockIndexRoute = AppStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AppRoute,
} as any)
const AppStockMouvementsRoute = AppStockMouvementsRouteImport.update({
  id: '/stock/mouvements',
  path: '/stock/mouvements',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueFournisseursRoute =
  AppCatalogueFournisseursRouteImport.update({
    id: '/catalogue/fournisseurs',
    path: '/catalogue/fournisseurs',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogueCategoriesRoute = AppCatalogueCategoriesRouteImport.update({
  id: '/catalogue/categories',
  path: '/catalogue/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationUtilisateursRoute =
  AppAdministrationUtilisateursRouteImport.update({
    id: '/administration/utilisateurs',
    path: '/administration/utilisateurs',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationParametresRoute =
  AppAdministrationParametresRouteImport.update({
    id: '/administration/parametres',
    path: '/administration/parametres',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationEntrepotsRoute =
  AppAdministrationEntrepotsRouteImport.update({
    id: '/administration/entrepots',
    path: '/administration/entrepots',
    getParentRoute: () => AppRoute,
  } as any)
const AppStockReceptionsIndexRoute = AppStockReceptionsIndexRouteImport.update({
  id: '/stock/receptions/',
  path: '/stock/receptions/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueProduitsIndexRoute =
  AppCatalogueProduitsIndexRouteImport.update({
    id: '/catalogue/produits/',
    path: '/catalogue/produits/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogueProduitsProductIdRoute =
  AppCatalogueProduitsProductIdRouteImport.update({
    id: '/catalogue/produits/$productId',
    path: '/catalogue/produits/$productId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/mon-compte': typeof AppMonCompteRoute
  '/administration/entrepots': typeof AppAdministrationEntrepotsRoute
  '/administration/parametres': typeof AppAdministrationParametresRoute
  '/administration/utilisateurs': typeof AppAdministrationUtilisateursRoute
  '/catalogue/categories': typeof AppCatalogueCategoriesRoute
  '/catalogue/fournisseurs': typeof AppCatalogueFournisseursRoute
  '/stock/mouvements': typeof AppStockMouvementsRoute
  '/stock/': typeof AppStockIndexRoute
  '/catalogue/produits/$productId': typeof AppCatalogueProduitsProductIdRoute
  '/catalogue/produits/': typeof AppCatalogueProduitsIndexRoute
  '/stock/receptions/': typeof AppStockReceptionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mon-compte': typeof AppMonCompteRoute
  '/': typeof AppIndexRoute
  '/administration/entrepots': typeof AppAdministrationEntrepotsRoute
  '/administration/parametres': typeof AppAdministrationParametresRoute
  '/administration/utilisateurs': typeof AppAdministrationUtilisateursRoute
  '/catalogue/categories': typeof AppCatalogueCategoriesRoute
  '/catalogue/fournisseurs': typeof AppCatalogueFournisseursRoute
  '/stock/mouvements': typeof AppStockMouvementsRoute
  '/stock': typeof AppStockIndexRoute
  '/catalogue/produits/$productId': typeof AppCatalogueProduitsProductIdRoute
  '/catalogue/produits': typeof AppCatalogueProduitsIndexRoute
  '/stock/receptions': typeof AppStockReceptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/mon-compte': typeof AppMonCompteRoute
  '/_app/': typeof AppIndexRoute
  '/_app/administration/entrepots': typeof AppAdministrationEntrepotsRoute
  '/_app/administration/parametres': typeof AppAdministrationParametresRoute
  '/_app/administration/utilisateurs': typeof AppAdministrationUtilisateursRoute
  '/_app/catalogue/categories': typeof AppCatalogueCategoriesRoute
  '/_app/catalogue/fournisseurs': typeof AppCatalogueFournisseursRoute
  '/_app/stock/mouvements': typeof AppStockMouvementsRoute
  '/_app/stock/': typeof AppStockIndexRoute
  '/_app/catalogue/produits/$productId': typeof AppCatalogueProduitsProductIdRoute
  '/_app/catalogue/produits/': typeof AppCatalogueProduitsIndexRoute
  '/_app/stock/receptions/': typeof AppStockReceptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mon-compte'
    | '/administration/entrepots'
    | '/administration/parametres'
    | '/administration/utilisateurs'
    | '/catalogue/categories'
    | '/catalogue/fournisseurs'
    | '/stock/mouvements'
    | '/stock/'
    | '/catalogue/produits/$productId'
    | '/catalogue/produits/'
    | '/stock/receptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mon-compte'
    | '/'
    | '/administration/entrepots'
    | '/administration/parametres'
    | '/administration/utilisateurs'
    | '/catalogue/categories'
    | '/catalogue/fournisseurs'
    | '/stock/mouvements'
    | '/stock'
    | '/catalogue/produits/$productId'
    | '/catalogue/produits'
    | '/stock/receptions'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/mon-compte'
    | '/_app/'
    | '/_app/administration/entrepots'
    | '/_app/administration/parametres'
    | '/_app/administration/utilisateurs'
    | '/_app/catalogue/categories'
    | '/_app/catalogue/fournisseurs'
    | '/_app/stock/mouvements'
    | '/_app/stock/'
    | '/_app/catalogue/produits/$productId'
    | '/_app/catalogue/produits/'
    | '/_app/stock/receptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-compte': {
      id: '/_app/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AppMonCompteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/': {
      id: '/_app/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AppStockIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/mouvements': {
      id: '/_app/stock/mouvements'
      path: '/stock/mouvements'
      fullPath: '/stock/mouvements'
      preLoaderRoute: typeof AppStockMouvementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/fournisseurs': {
      id: '/_app/catalogue/fournisseurs'
      path: '/catalogue/fournisseurs'
      fullPath: '/catalogue/fournisseurs'
      preLoaderRoute: typeof AppCatalogueFournisseursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/categories': {
      id: '/_app/catalogue/categories'
      path: '/catalogue/categories'
      fullPath: '/catalogue/categories'
      preLoaderRoute: typeof AppCatalogueCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/utilisateurs': {
      id: '/_app/administration/utilisateurs'
      path: '/administration/utilisateurs'
      fullPath: '/administration/utilisateurs'
      preLoaderRoute: typeof AppAdministrationUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/parametres': {
      id: '/_app/administration/parametres'
      path: '/administration/parametres'
      fullPath: '/administration/parametres'
      preLoaderRoute: typeof AppAdministrationParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/entrepots': {
      id: '/_app/administration/entrepots'
      path: '/administration/entrepots'
      fullPath: '/administration/entrepots'
      preLoaderRoute: typeof AppAdministrationEntrepotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/receptions/': {
      id: '/_app/stock/receptions/'
      path: '/stock/receptions'
      fullPath: '/stock/receptions/'
      preLoaderRoute: typeof AppStockReceptionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/produits/': {
      id: '/_app/catalogue/produits/'
      path: '/catalogue/produits'
      fullPath: '/catalogue/produits/'
      preLoaderRoute: typeof AppCatalogueProduitsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/produits/$productId': {
      id: '/_app/catalogue/produits/$productId'
      path: '/catalogue/produits/$productId'
      fullPath: '/catalogue/produits/$productId'
      preLoaderRoute: typeof AppCatalogueProduitsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMonCompteRoute: typeof AppMonCompteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdministrationEntrepotsRoute: typeof AppAdministrationEntrepotsRoute
  AppAdministrationParametresRoute: typeof AppAdministrationParametresRoute
  AppAdministrationUtilisateursRoute: typeof AppAdministrationUtilisateursRoute
  AppCatalogueCategoriesRoute: typeof AppCatalogueCategoriesRoute
  AppCatalogueFournisseursRoute: typeof AppCatalogueFournisseursRoute
  AppStockMouvementsRoute: typeof AppStockMouvementsRoute
  AppStockIndexRoute: typeof AppStockIndexRoute
  AppCatalogueProduitsProductIdRoute: typeof AppCatalogueProduitsProductIdRoute
  AppCatalogueProduitsIndexRoute: typeof AppCatalogueProduitsIndexRoute
  AppStockReceptionsIndexRoute: typeof AppStockReceptionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMonCompteRoute: AppMonCompteRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdministrationEntrepotsRoute: AppAdministrationEntrepotsRoute,
  AppAdministrationParametresRoute: AppAdministrationParametresRoute,
  AppAdministrationUtilisateursRoute: AppAdministrationUtilisateursRoute,
  AppCatalogueCategoriesRoute: AppCatalogueCategoriesRoute,
  AppCatalogueFournisseursRoute: AppCatalogueFournisseursRoute,
  AppStockMouvementsRoute: AppStockMouvementsRoute,
  AppStockIndexRoute: AppStockIndexRoute,
  AppCatalogueProduitsProductIdRoute: AppCatalogueProduitsProductIdRoute,
  AppCatalogueProduitsIndexRoute: AppCatalogueProduitsIndexRoute,
  AppStockReceptionsIndexRoute: AppStockReceptionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
